name: CI
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ^14
      - run: make deps
      - run: make build
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: make test
